language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  - UPGRADE=none
  - UPGRADE=7.x-1.6
  - UPGRADE=7.x-1.5
  - UPGRADE=7.x-1.4
  - UPGRADE=7.x-1.2
  - UPGRADE=7.x-1.1
  - UPGRADE=7.x-1.0-rc5
  - UPGRADE=7.x-1.0-rc4
  - UPGRADE=7.x-1.0-rc3

matrix:
  fast_finish: true
  allow_failures:
    - env: UPGRADE=7.x-1.0-rc3

install:
  - export UPDATE TRAVIS_BUILD_DIR
  - cp scripts/travis-ci.sh $HOME/
  - ./travis-ci.sh system-install

before_script:
  - ./travis-ci.sh before-tests

script:
  - ./travis-ci.sh run-tests

after_script:
  - ./travis-ci.sh after-tests

#notifications:
#  email:
#    recipients:
#      - panopoly-ci@googlegroups.com
#    on_success: always
#    on_failure: always
#  irc:
#    channels:
#      - "chat.freenode.net#panopoly"
#    on_success: always
#    on_failure: always
